services:
  wecom-kf:
    build: .
    container_name: wecom-kf
    ports:
      - '3000:3000'
    environment:
      # 服务配置
      - NODE_ENV=production
      - PORT=3000

      # 企业微信配置
      - WECOM_CORPID=${WECOM_CORPID}
      - WECOM_SECRET=${WECOM_SECRET}
      - WECOM_TOKEN=${WECOM_TOKEN}
      - WECOM_ENCODING_AES_KEY=${WECOM_ENCODING_AES_KEY}

      # OpenAI 配置
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}

      # 讯飞配置
      - IFLYTEK_APP_ID=${IFLYTEK_APP_ID}
      - IFLYTEK_API_KEY=${IFLYTEK_API_KEY}
      - IFLYTEK_API_SECRET=${IFLYTEK_API_SECRET}
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    restart: unless-stopped
